version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env-file: 
      -server/.env

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      -backend